import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#FAF0DC" },
  container: { flex: 1 },
  webWrapper: {
    maxWidth: 800,
    width: "100%",
    alignSelf: "center",
    flex: 1,
    paddingHorizontal: Platform.OS === "web" ? 16 : 0,
  },
  loading: { flex: 1, justifyContent: "center", alignItems: "center" },
  loadingText: { fontSize: 18, color: "#550000" },

  header: {
    paddingHorizontal: 24,
    paddingTop: Platform.OS === "ios" ? 50 : 30,
    paddingBottom: 10,
  },
  headerTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  logoRow: { flexDirection: "row", alignItems: "center" },
  logo: { width: 24, height: 24, marginRight: 10 },
  headerText: { color: "#550000", fontSize: 20, fontWeight: "800" },
  profileBtn: {
   // backgroundColor: "#550000",
   // paddingHorizontal: 16,
    //paddingVertical: 8,
   // borderRadius: 20,
   flexDirection:"row",
   alignItems:"center",
   justifyContent:"center",
   gap:10,
  },
  profileIcon:{
    width:32,
    height:32,
  },
  profileText: { color: "#550000", fontWeight: "700", fontSize: 14 },

  title: {
    fontSize: 28,
    fontWeight: "800",
    color: "#550000",
    textAlign: "center",
  },

  searchInput: {
    marginTop: 14,
    height: 50,
    borderRadius: 12,
    paddingHorizontal: 16,
    backgroundColor: "#ffffff50",
    borderWidth: 1,
    borderColor: "#55000040",
    color: "#550000",
    fontSize: 16,
  },

  listContainer: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 120,
  },

  cardWrapper: {
    marginBottom: 18,
    backgroundColor: "#ffffff50",
    borderRadius: 16,
    overflow: "hidden",
    elevation: 5,
    flexDirection: "row",
  },
  card: {
    flexDirection: "row",
    padding: 14,
    flex: 1,
  },
  cover: { width: 100, height: 140, borderRadius: 8 },
  coverPlaceholder: {
    width: 100,
    height: 140,
    backgroundColor: "#ffffff40",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 8,
  },
  coverInitials: { fontSize: 32, fontWeight: "800", color: "#550000" },
  cardContent: { flex: 1, paddingLeft: 14, justifyContent: "center" },
  cardTitle: { fontSize: 18, fontWeight: "700", color: "#550000" },
  cardAuthor: { fontSize: 14, color: "#550000aa", marginTop: 4 },
  statusBadge: {
    marginTop: 8,
    fontSize: 13,
    fontWeight: "600",
    color: "#550000",
    backgroundColor: "#55000020",
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
  },
  deleteBtn: {
    backgroundColor: "#ff4444",
    paddingVertical: 14,
    justifyContent: "center",
    alignItems: "center",
    width: 90,
  },
  deleteBtnText: { color: "white", fontWeight: "700" },

  footer: {
    position: "absolute",
    bottom: 20,
    left: 0,
    right: 0,
    alignItems: "center",
  },
  primaryButton: {
    flexDirection: "row",
    backgroundColor: "#550000",
    paddingHorizontal: 24,
    paddingVertical: 16,
    borderRadius: 30,
    alignItems: "center",
    elevation: 10,
  },
  primaryButtonText: { color: "#FAF0DC", fontSize: 18, fontWeight: "700" },
  primaryButtonIcon: { color: "#FAF0DC", fontSize: 24, marginLeft: 8 },

  emptyContainer: { padding: 40, alignItems: "center" },
  emptyTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#550000",
    marginBottom: 10,
    textAlign: "center",
  },
  emptySubtitle: {
    fontSize: 15,
    color: "#550000aa",
    textAlign: "center",
    marginBottom: 20,
  },
  emptyAddBtn: {
    backgroundColor: "#550000",
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 25,
  },
  emptyAddText: { color: "#FAF0DC", fontWeight: "700" },

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContent: {
    backgroundColor: "white",
    borderRadius: 20,
    padding: 24,
    width: "100%",
    maxWidth: 400,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#550000",
    marginBottom: 12,
    textAlign: "center",
  },
  modalMessage: {
    fontSize: 16,
    color: "#550000",
    marginBottom: 24,
    lineHeight: 22,
    textAlign: "center",
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 12,
  },
  modalButton: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    minWidth: 100,
    alignItems: "center",
  },
  cancelButton: { backgroundColor: "#f0f0f0" },
  confirmButton: { backgroundColor: "#ff4444" },
  cancelButtonText: { color: "#550000", fontWeight: "600", fontSize: 16 },
  confirmButtonText: { color: "white", fontWeight: "600", fontSize: 16 },
});
