import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#FAF0DC" },
  gradient: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 30,
  },
  formContainer: {
    width: "85%",
    maxWidth: 360,
    alignSelf: "center",
    alignItems: "center",
  },
  title: {
    fontSize: 30,
    fontWeight: "800",
    color: "#550000",
    textAlign: "center",
    marginBottom: 8,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  subtitle: {
    color: "#550000",
    marginBottom: 30,
    textAlign: "center",
    fontStyle: "italic",
  },
  inputLabel: {
    alignSelf: "flex-start",
    color: "#550000",
    marginBottom: 5,
    fontWeight: "600",
  },
  input: {
    width: "100%",
    height: 50,
    borderWidth: 1,
    borderColor: "#55000050",
    borderRadius: 12,
    paddingLeft: 14,
    color: "#550000",
    backgroundColor: "#ffffff20",
  },
  passwordContainer: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#55000050",
    borderRadius: 12,
    backgroundColor: "#ffffff20",
    height: 50,
    paddingHorizontal: 10,
  },
  passwordInput: { flex: 1, color: "#550000" },
  showText: { color: "#550000", fontWeight: "600", fontSize: 14 },
  errorText: {
    color: "red",
    textAlign: "center",
    marginTop: 10,
    marginBottom: 10,
    fontWeight: "500",
  },
  optionsContainer: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 25,
    marginTop: 10,
  },
  loginButton: {
    backgroundColor: "#550000",
    paddingVertical: 14,
    borderRadius: 25,
    width: "100%",
    shadowColor: "#550000",
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8,
    marginBottom: 18,
  },
  loginText: {
    textAlign: "center",
    color: "#FAF0DC",
    fontWeight: "700",
    fontSize: 17,
  },
  signupText: {
    color: "#550000",
    textAlign: "center",
    fontSize: 15,
    marginBottom: 25,
  },
});

export default styles;
