import { StyleSheet, Platform } from "react-native";

const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: "#FAF0DC",
  },
  container: {
    flex: 1,
  },
  scroll: {
    paddingHorizontal: 24,
    paddingBottom: 60,
  },
  header: {
    marginTop: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  backBtn: {
    color: "#550000",
    fontSize: 26,
    fontWeight: "700",
  },
  flex__container: {
    flexDirection: "column",
    alignItems: "center",
    gap: 30,
    marginTop: 30,
  },
  avatar: {
    flexDirection: "column",
    alignItems: "center",
    gap: 5,
  },
  avatar__image: {
    width: 120,
    height: 120,
    marginBottom: 10,
  },
  avatar__name: {
    color: "#550000",
    fontSize: 26,
    fontWeight: "700",
  },
  avatar__email: {
    color: "#550000",
    fontSize: 16,
    fontWeight: "500",
    opacity: 0.6,
  },
  book__stats: {
    flexDirection: "row",
    alignItems: "center",
    gap: 15,
  },
  book__active: {
    width: 90,
    height: 110,
    backgroundColor: "#550000",
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  active__num: {
    fontSize: 28,
    color: "#FAF0DC",
    fontWeight: "700",
  },
  active__desc: {
    fontSize: 16,
    color: "#FAF0DC",
    fontWeight: "500",
  },
  book__pending: {
    width: 90,
    height: 110,
    backgroundColor: "#E6D9B8",
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  pending__num: {
    fontSize: 28,
    color: "#550000",
    fontWeight: "700",
  },
  pending__desc: {
    fontSize: 16,
    color: "#550000",
    fontWeight: "500",
  },
  book__completed: {
    width: 90,
    height: 110,
    backgroundColor: "#E6D9B8",
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  completed__num: {
    fontSize: 28,
    color: "#550000",
    fontWeight: "700",
  },
  completed__desc: {
    fontSize: 16,
    color: "#550000",
    fontWeight: "500",
  },
  profile__options: {
    width: 305,
    height: 250,
    borderRadius: 20,
    padding: 15,
    paddingTop: 7,
    backgroundColor: "#FCF7E6",
    justifyContent: "space-around",
  },
  profile__option: {
    flexDirection: "row",
    gap: 95,
    alignItems: "center",
    paddingBottom: 15,
    paddingTop: 15,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(85,0,0,0.1)",
  },

  profile__option__end: {
    borderBottomWidth: 0,
    gap: 55,
  },
  option__icon: {
    flexDirection: "row",
    gap: 15,
    alignItems: "center",
  },
  option__image: {
    width: 32,
    height: 32,
  },
  option__info: {
    marginTop: 20,
    flexDirection: "column",
    gap: 4,
  },
  info__title: {
    fontSize: 16,
    fontWeight: "700",
    color: "#550000",
  },
  info__text: {
    flexDirection: "column",
    gap: 2,
  },
  info__desc: {
    fontSize: 14,
    opacity: 0.6,
    color: "#550000",
  },
  option__nav: {},
  nav__arrow: {
    width: 18,
    height: 18,
  },
  logoutBtn: {
    marginTop: 20,
    backgroundColor: "#550000",
    paddingVertical: 14,
    paddingHorizontal: 40,
    borderRadius: 20,
  },
  logoutText: {
    color: "#FAF0DC",
    fontSize: 18,
    fontWeight: "700",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContent: {
    backgroundColor: "white",
    borderRadius: 20,
    padding: 24,
    width: "100%",
    maxWidth: 400,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#550000",
    marginBottom: 12,
    textAlign: "center",
  },
  modalMessage: {
    fontSize: 16,
    color: "#550000",
    marginBottom: 24,
    lineHeight: 22,
    textAlign: "center",
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 12,
  },
  modalButton: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    minWidth: 100,
    alignItems: "center",
  },
  cancelButton: { backgroundColor: "#f0f0f0" },
  confirmButton: { backgroundColor: "#ff4444" },
  cancelButtonText: { color: "#550000", fontWeight: "600", fontSize: 16 },
  confirmButtonText: { color: "white", fontWeight: "600", fontSize: 16 },
});

export default styles;
