import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: "transparent",
  },
  container: {
    flex: 1,
    alignSelf: "center",
    width: "100%",
  },
  innerContainer: {
    flex: 1,
    maxWidth: 600,
    alignSelf: "center",
    width: "100%",
  },
  scroll: {
    paddingHorizontal: 24,
    paddingBottom: 60,
  },
  header: {
    marginTop: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 30,
  },
  backBtn: {
    color: "#550000",
    fontSize: 26,
    fontWeight: "700",
  },
  pageTitle: {
    color: "#550000",
    fontSize: 24,
    fontWeight: "800",
    position: "absolute",
    left: 0,
    right: 0,
    textAlign: "center",
    zIndex: -1,
  },
  contentContainer: {
    gap: 30,
  },
  settingItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#FCF7E6",
    padding: 18,
    borderRadius: 20,
  },
  settingInfo: {
    flex: 1,
  },
  settingTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#550000",
  },
  settingDesc: {
    fontSize: 14,
    color: "#550000",
    opacity: 0.6,
    marginTop: 4,
  },
  notificationContainer: {
    backgroundColor: "#FCF7E6",
    padding: 18,
    borderRadius: 20,
  },
  notificationTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#550000",
    marginBottom: 10,
  },
   notificationSubItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    paddingHorizontal: 12,
    backgroundColor: "rgba(255, 255, 255, 0.5)",
    borderRadius: 12,
    marginBottom: 5,
  },
  settingSubTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#550000",
  },
  notificationBtn: {
    backgroundColor: "#550000",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 10,
  },
  passwordSection: {
    backgroundColor: "#FCF7E6",
    padding: 24,
    borderRadius: 20,
    gap: 16,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#550000",
    marginBottom: 8,
  },
  input: {
    backgroundColor: "#FAF0DC",
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 12,
    fontSize: 16,
    color: "#550000",
    borderWidth: 1,
    borderColor: "rgba(85, 0, 0, 0.1)",
  },
  saveButton: {
    backgroundColor: "#550000",
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 10,
  },
  saveButtonText: {
    color: "#FAF0DC",
    fontSize: 18,
    fontWeight: "700",
  },
  saveButtonDisabled: {
    opacity: 0.6,
  },
  errorText: {
    color: "#D32F2F",
    fontSize: 14,
    marginTop: 8,
    fontWeight: "500",
  },
  successText: {
    color: "#388E3C",
    fontSize: 14,
    marginTop: 8,
    fontWeight: "500",
  },
  infoContainer: {
    marginTop: 50,
    paddingHorizontal: 20,
    alignItems: "center",
    width: "100%",
  },
  infoItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(85, 0, 0, 0.1)",
  },
  infoLabel: {
    fontSize: 16,
    color: "#550000",
    fontWeight: "600",
  },
  infoValue: {
    fontSize: 16,
    color: "#550000",
    opacity: 0.8,
  },
  infoFooter: {
    marginTop: 20,
    fontSize: 15,
    color: "#550000",
    fontStyle: "italic",
    textAlign: "center",
    opacity: 0.7,
  },
  copyright: {
    marginTop: 10,
    fontSize: 12,
    color: "#550000",
    opacity: 0.5,
    textAlign: "center",
  },

});

export default styles;
